const { client } = require('./connections.js');

const SQL = `
CREATE TABLE IF NOT EXISTS genre (
    genreID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS author (
    authorID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS manga (
    mangaID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    authorID INTEGER NOT NULL REFERENCES author(authorID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS mangaGenres (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mangaID INTEGER NOT NULL REFERENCES manga ( mangaID ) ON DELETE CASCADE,
    genreID INTEGER NOT NULL REFERENCES genre ( genreID )  ON DELETE CASCADE
);
`

async function main(){

    await client.connect();
    await client.query(SQL);
    await client.end();
    console.log('The database tables have been recreated.');

}

main();

